version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: docker:stable

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          echo "Building Docker image..."
          docker build -t auroradreamer/circleci-assignment .
      - run: |
          echo "Logging in to Docker Hub..."
          echo $DOCKER_HUB_TOKEN | docker login -u auroradreamer --password-stdin
          echo "Pushing Docker image..."
          docker tag auroradreamer/circleci-assignment:latest auroradreamer/circleci-assignment:latest
          docker push auroradreamer/circleci-assignment:latest

workflows:
  build-and-deploy-workflow:
    jobs:
      - build-and-deploy
